### ISSUE TITLE
Looking for implementing this project by hand !!

### ISSUE THREAD

**Issue by sabhi27** [shoumikgoswami/Machine-learning-Voice-Assistant#1]
Hi @shoumikgoswami , You have done awesome work. I would like to carry this on. Is this repository completely executable and contains all required files for execution ? I went through all demo_videos and found v-0.3. Which version is this particular repo supports ?
Looking for your reply ASAP. Thanks in advance !

**Comment by shoumikgoswami** [comment]
Hey thank you!! 
Please feel free to use this repo.
The implementation should work but you may have version issues with Rasa, they release new versions very frequently. 
Also, I would really love to see what you make out of it, so do let me know if possible ;)
Thanks!
